# -*- coding: utf-8 -*-
"""Cert_Py.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NRj-6pJ38nuxD6UFAczO5DYGWZTiIO9F
"""

from google.colab import drive
drive.mount('/gdrive', force_remount=True)

import pandas as pd
from PIL import Image, ImageDraw, ImageFont

data = pd.read_excel('/gdrive/My Drive/cert/Cert_Copy.xlsx')

name_list = data["Name"].tolist()

for i in name_list:
    im = Image.open('/gdrive/My Drive/cert/cert.jpg')
    d = ImageDraw.Draw(im)
    location = (1117, 1201)
    text_color = (0, 137, 209)
    font = ImageFont.truetype("/gdrive/My Drive/cert/Fonts/Afternoon in Stereo Personal Use.ttf",120)   #load_default()
    d.text(location, i, fill = text_color, font = font)
    im.save("/gdrive/My Drive/cert/Certificates/certificate_" + i + ".pdf")